import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Providers from "./providers";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

function getBaseUrl() {
  if (typeof window !== "undefined") return window.location.origin;
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;
  return `http://localhost:${process.env.PORT ?? 3000}`;
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const heads = await headers();
  const cookie = heads.get("Cookie") ?? undefined;
  const baseUrl = getBaseUrl();

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <Providers baseUrl={baseUrl} cookie={cookie}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
